from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, EmailStr, Field

# student self registration
class StudentRegister(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    email: EmailStr
    password: str = Field(..., min_length=8)
    full_name: Optional[str] = None

# admin invites teacher: only full_name + email required
# username and password are auto-generated by the system
class TeacherInvite(BaseModel):
    full_name: str = Field(..., min_length=1, max_length=100)
    email: EmailStr

# user response
class UserResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    username: str
    email: str
    full_name: Optional[str]
    role: str
    is_active: bool
    email_sent: bool